import { defineConfig } from 'windicss/helpers'
import plugin from 'windicss/plugin'

export default defineConfig({
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: 'var(--background-color)',
        surface: 'var(--surface-color)',
        primary: 'var(--primary-color)',
        'primary-50': 'var(--primary-50)',
        'primary-100': 'var(--primary-100)',
        'primary-200': 'var(--primary-200)',
        'primary-300': 'var(--primary-300)',
        'primary-400': 'var(--primary-400)',
        'primary-500': 'var(--primary-500)',
        'primary-600': 'var(--primary-600)',
        'primary-700': 'var(--primary-700)',
        'primary-800': 'var(--primary-800)',
        'primary-900': 'var(--primary-900)',
        'gray-50': 'var(--gray-50)',
        'gray-100': 'var(--gray-100)',
        'gray-200': 'var(--gray-200)',
        'gray-300': 'var(--gray-300)',
        'gray-400': 'var(--gray-400)',
        'gray-500': 'var(--gray-500)',
        'gray-600': 'var(--gray-600)',
        'gray-700': 'var(--gray-700)',
        'gray-800': 'var(--gray-800)',
        'gray-900': 'var(--gray-900)',
        'green-50': '#e0f2f1',
        'green-100': '#b2dfdb',
        'green-200': '#80cbc4',
        'green-300': '#4db6ac',
        'green-400': '#26a69a',
        'green-500': '#009688',
        'green-600': '#00897b',
        'green-700': '#00796b',
        'green-800': '#00695c',
        'green-900': '#004d40',
        'red-50': '#ffebee',
        'red-100': '#ffcdd2',
        'red-200': '#ef9a99',
        'red-300': '#e57372',
        'red-400': '#ef534f',
        'red-500': '#f44334',
        'red-600': '#e53934',
        'red-700': '#d32f2e',
        'red-800': '#c62827',
        'red-900': '#b71c1b',
        label: 'rgba(var(--label-tuple), var(--label-opacity))',
        'label-medium': 'rgba(var(--label-tuple), .6)',
        'label-disabled': 'rgba(var(--label-tuple), .38)',
        'label-divider': 'rgba(var(--label-tuple), .12)',
        'label-well': 'rgba(var(--label-tuple), .06)',
      },
    },
  },
  plugins: [
    require('windicss/plugin/forms'),
    plugin(({ addUtilities }) => {
      addUtilities({
        '.states': {
          '--state-opacity': '0.0',
          '&:hover': {
            '--state-opacity': '0.04',
          },
          '&:active': {
            '--state-opacity': '0.10',
          },
          '&:focus': {
            '--state-opacity': '0.12',
            boxShadow: '0 0 0 2px var(--primary-600)',
            outline: 'none !important',
          },
          "&:disabled, &[aria-disabled='true']": {
            '--state-opacity': '0.0',
            '--tw-text-opacity': '0.38',
          },
          position: 'relative',
          overflow: 'hidden',
          '&:after': {
            content: "''",
            position: 'absolute',
            top: '0',
            left: '0',
            right: '0',
            bottom: '0',
            background: 'rgba(var(--label-tuple), var(--state-opacity, 0))',
            pointerEvents: 'none',
            transition: 'background 75ms linear',
          },
        },
        '.bg-states': {
          'background-color':
            'rgba(var(--label-tuple), var(--state-opacity, 0))',
        },
        '.label-white': {
          '--label-tuple': '255, 255, 255',
        },
        '.label-black': {
          '--label-tuple': '0, 0, 0',
        },
        '.surface-primary': {
          '--background-color': 'var(--primary-100)',
          '--surface-color': 'var(--primary-50)',
          '.dark &': {
            '--surface-color': 'var(--primary-800)',
            '--background-color': 'var(--primary-900)',
          },
        },
        '.surface-light': {
          '--surface-color': 'var(--gray-50)',
          '--background-color': 'var(--gray-100)',
        },
        '.surface-dark': {
          '--surface-color': 'var(--gray-800)',
          '--background-color': 'var(--gray-900)',
        },
      })
    }),
  ],
  safelist: [
    '!hover:text-label',
    '-translate-x-1/2',
    '-translate-x-full',
    'absolute',
    'bg-black',
    'bg-opacity-50',
    'duration-100',
    'duration-1000',
    'duration-150',
    'duration-200',
    'duration-300',
    'ease-in',
    'ease-out',
    'fixed',
    'flex',
    'flex-col',
    'font-medium',
    'font-mono',
    'group',
    'group-hover:text-label-medium',
    'h-10',
    'h-6',
    'h-screen',
    'hover:text-label',
    'inset-0',
    'inset-x-0',
    'items-center',
    'items-end',
    'justify-center',
    'leading-10',
    'left-1/2',
    'lg:max-w-3xl',
    'max-w-lg',
    'max-w-md',
    'max-w-xs',
    'md:hidden',
    'ml-2',
    'ml-4',
    'ml-auto',
    'mr-2',
    'mr-auto',
    'mt-3',
    'mt-6',
    'mx-16',
    'sm:mx-0',
    'opacity-0',
    'opacity-100',
    'origin-top-right',
    'p-2',
    'pl-2',
    'pr-2',
    'px-2',
    'relative',
    'ring-1',
    'ring-2',
    'ring-primary',
    'rounded-2xl',
    'rounded-full',
    'rounded-xl',
    'scale-100',
    'scale-95',
    'sm:items-center',
    'sm:px-0',
    'sm:translate-y-0',
    'sm:scale-95',
    'space-x-10',
    'text-base',
    'text-center',
    'text-label',
    'text-label-disabled',
    'text-label-divider',
    'text-label-medium',
    'text-sm',
    'text-xs',
    'top-0',
    'transform',
    'transition',
    'translate-x-0',
    'translate-y-0',
    'translate-y-1',
    'translate-y-4',
    'truncate',
    'w-10',
    'w-6',
    'w-full',
    'w-screen',
    'z-10',
    'z-20',
  ],
})
